language: go

install:
  - sudo apt-get update
  - sudo apt-get install libtool pkg-config build-essential autoconf automake
  - sudo apt-get install libzmq-dev
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure && make check
  - sudo make install
  - sudo ldconfig
  - cd ../
  - wget https://github.com/zeromq/libzmq/releases/download/v4.2.2/zeromq-4.2.2.tar.gz
  - tar -xvf zeromq-4.2.2.tar.gz
  - cd zeromq-4.2.2
  - ./autogen.sh
  - ./configure && make check
  - sudo make install
  - sudo ldconfig
  - cd ../
  - go get golang.org/x/tools/cmd/cover

script:
  - make test

go:
  - 1.7
  - 1.8
